### ISSUE TITLE
Missing null check when source object call method

### ISSUE THREAD

**Issue by DamianResler** [fluentsprings/ExpressMapper#121]
ExpressMapper.Mapper.Register<PrintedPostRequest, ReprintListGridElement>()
        .Member(x => x.AddressCol, r => r.Address.GetLinesString(" "))
        .Member(x => x.ComputedCol, r => r.ProcessedDate.ToShortDateString()));

when ProcessedDate is null, null reference exception is thrown.

**Comment by JonPSmith** [comment]
Hi @DamianResler,

I don't think that is an ExpressMapper issue, its because you call `.ToShortDateString()` on ProcessedDate. If you are using the latest C#/Visual Studio you could write `r.ProcessedDate?.ToShortDateString()` which will return null, or if not null then it will call `.ToShortDateString()` and return a string.

**Comment by anisimovyuriy** [comment]
@DamianResler - thanks for the question! Expressmapper actually checks nested complex type properties for null - in that case is just nullable simple type property and I agree with @JonPSmith on this.
Did it solve your problem?
